Substitution Cypher
========================================================


## Step 1, the Key
```{r}
key <- "zoo"
first <- function(L){which (L==letters)}
paste(sapply(unlist(strsplit(key,split=NULL)),FUN=first),collapse="")
```

```{r}
first("zoo")
```

## Step 2, the Cypher
```{r}
set.seed(paste(sapply(unlist(strsplit(key,split=NULL)),FUN=first),collapse=""))
characters <- c(letters, LETTERS,".",":",",",";",0:9)
fromandto<-sample(characters)
fromandto
```

## Step 3, the Encryption
```{r}
encrypt<-chartr(paste(characters,collapse=""),paste(fromandto,collapse=""),"Cannot read this")
encrypt
```

## Step 4, the Decryption
```{r}
decoded<-chartr(paste(fromandto,collapse=""),paste(characters,collapse=""),encrypt)
decoded
```

## The Paragraph
```{r}
paragraph<-chartr(paste(characters,collapse=""),paste(fromandto,collapse=""),"Many many sentences which you will not be able to read.  This class has now taught me to encrypt things, which actually makes me feel like a spy.  Possibly I could use this in the CIA? I would never work for the CIA, I am not sneaky enough.")
paragraph

decoded<-chartr(paste(fromandto,collapse=""),paste(characters,collapse=""),paragraph)
decoded
```