Tool Tips
========================================================

## formatWord Function
```{r results='asis'}

formatWord <- function(word,trans,class1){
  if (is.na(trans))
    return(word)
  test1 <- paste("<span class='",class1,"' ",sep="")
  test2 <- paste(test1, "title='",trans,"'>",sep="")
  test3 <- paste(test2,word,"</span>",sep="")
return(test3)
}
```

## Testing
```{r results= 'asis'}
cat(formatWord("Hello","hi there!","hiword"))

cat(formatWord("Hello","hi there!",class="hiword"),"to","all","of","you","in",
    formatWord("Television Land.","TV Viewers","hiword"))
```

## FormatString Function
```{r results = 'asis'}
formatString <- function(word, tips, styles){
  results <- c()
  for (k in 1:length(word)){
    results[k] <- formatWord(word[k],tips[k],styles[k])
  }
  return(cat(results))
}

```

## Testing
```{r results = 'asis'}
formatString(c("How","now","brown","cow","!"),c("How are you doing?",NA,"Why brown?","bovine","enthusiasm"),c("hiword","","brown","blue","hiword"))
